# codelists defining spelling of all used provinces and antibiotics names


codelists <- list(
  provinces = c(
    "Anhui",
    "Beijing",
    "Chongqing",
    "Fujian",
    "Gansu",
    "Guangdong",
    "Guangxi",
    "Guizhou",
    "Hainan",
    "Hebei",
    "Heilongjiang",
    "Henan",
    "Hong Kong",
    "Hubei",
    "Hunan",
    "Inner Mongolia",
    "Jiangsu",
    "Jiangxi",
    "Jilin",
    "Liaoning",
    "Ningxia",
    "Qinghai",
    "Shaanxi",
    "Shandong",
    "Shanghai",
    "Shanxi",
    "Sichuan",
    "Tianjin",
    "Tibet",
    "Xinjiang",
    #"Xizang", This is Tibet
    "Yunnan",
    "Zhejiang"
  ),
  antibiotics = c(
    "Acetylspiramycin",
    "Amoxicillin",
    "Ampicillin",
    "Azithromycin",
    "Cefazolin",
    "Cefotaxime",
    "Cefoxitin",
    "Ceftriaxone",
    "Cephalexin",
    "Chloramphenicol",
    "Chlortetracycline",
    "Cinoxacin",
    "Ciprofloxacin",
    "Clarithromycin",
    "Clindamycin",
    "Cloxacillin",
    "Danofloxacin",
    "Demeclocycline",
    "Difloxacin",
    "Doxycycline",
    "Enoxacin",
    "Enrofloxacin",
    "Erythromycin",
    "Fleroxacin",
    "Florfenicol",
    "Flumequine",
    "Gatifloxacin",
    "Gentamicin",
    "Josamycin",
    "Leucomycin",
    "Levofloxacin",
    "Lincomycin",
    "Linezolid",
    "Lomefloxacin",
    "Mabofloxacin",
    "Marbofloxacin",
    "Mecillinam",
    "Methacycline",
    "Minocycline",
    "Moxifloxacin",
    "Nadifloxacin",
    "Nalidixic acid",
    "Nitrofurantoin",
    "Norfloxacin",
    "Ofloxacin",
    "Oxacillin",
    "Oxolinic acid",
    "Oxytetracycline",
    "Pefloxacin",
    "Penicillin G",
    "Penicillin V",
    "Pipemidic acid",
    "Rifampicin",
    "Roxithromycin",
    "Sarafloxacin",
    "Sparfloxacin",
    "Spectinomycin",
    "Spiramycin",
    "Streptomycin",
    "Sulfabenzamide",
    "Sulfacetamide",
    "Sulfachinoxaline",
    "Sulfachloropyridazine",
    "Sulfadiazine",
    "Sulfadimethoxine",        # kept (dropped Sulfadimethoxypyrimidine)
    "Sulfadoxine",
    "Sulfaguanidine",
    "Sulfamerazine",
    "Sulfameter",              # kept (dropped Sulfamethoxypyridazine)
    "Sulfamethazine",          # kept (dropped Sulfadimidine)
    "Sulfamethizole",
    "Sulfamethoxazole",
    "Sulfamethoxydiazine",     # kept (historical variant, distinct enough to retain)
    "Sulfamonomethoxine",
    "Sulfamoxole",
    "Sulfanilamide",
    "Sulfanitran",
    "Sulfaphenazole",
    "Sulfapyridine",
    "Sulfaquinoxaline",
    "Sulfathiazole",
    "Sulfisomidine",
    "Sulfisoxazole",
    "Teicoplanin",
    "Tetracycline",
    "Thiamphenicol",
    "Tilmicosin",
    "Tosufloxacin",
    "Trimethoprim",
    "Tylosin",
    "Vancomycin"
  )
)
